apiVersion: v1
kind: Service
metadata:
  name: sovereign-signal
  namespace: sovereign-signal
  labels:
    app: sovereign-signal
spec:
  selector:
    app: sovereign-signal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
